version: '3.8'

services:
  dark_reign_api:
    container_name: dark-reign-api
    image: dark-reign-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8002:80'
    networks:
      - traefik_proxy
      - default
    volumes:
      - .:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.jap_shop_mock.rule=Host(`dark-reign.net`) && PathPrefix(`/api`)"
      - "traefik.http.services.jap_shop_mock.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true
